name: Yasboot - System Tests with sanitizers

on:
  push:
    branches: [main]
  pull_request: 
    branches: [main]

jobs:
  execute_system_tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/matgla/yasboot:1.4
      credentials: 
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        sanitizer: [ENABLE_ASAN=ON, ENABLE_TSAN=ON, ENABLE_UBSAN=ON]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Prepare Yasboot project 
        shell: bash 
        run: |
          mkdir build 
      - name: Generate CMake project 
        shell: bash 
        working-directory: build
        run: |
          cmake .. -DUSE_CONFIG=host -DCMAKE_BUILD_TYPE=Debug -D${{ matrix.sanitizer }} -GNinja
      - name: Execute tests 
        shell: bash
        working-directory: build 
        run: 
          ninja st

