name: Yasboot - Target 

on:
  push:
    branches: [main]
  pull_request: 
    branches: [main]

jobs:
  execute_system_tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/matgla/yasboot:1.2
      credentials: 
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        config: [mspc]
    steps:
      - uses: actions/checkout@v2 
      - name: Prepare Yasboot project 
        shell: bash 
        run: |
          mkdir build 
      - name: Generate CMake project 
        shell: bash 
        working-directory: build
        run: |
          cmake .. -DUSE_CONFIG=${{ matrix.config }} -GNinja
      - name: Compile 
        shell: bash
        working-directory: build 
        run: 
          ninja 

